[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --dir /data --appendonly yes
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis-err.log

[program:backend]
command=java -jar /app/app.jar
environment=SPRING_PROFILES_ACTIVE="prod",REDIS_HOST="127.0.0.1",REDIS_PORT="6379",JWT_SECRET="suoha-prod-secret-change-me-in-production-32chars"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/backend.log
stderr_logfile=/var/log/supervisor/backend-err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-err.log
